// Attributes:
// - Visibility
// - Defense
// - Engine
// - Reactor

// Capacitors:
// - Defense
// - Speed
// -- Maximum depends on engine hardware
// -- Moving reduces current
// -- Current is fully replenished each round
// - Energy
// -- Maximum depends on reactor hardware and engineering skills
// -- Current is reduced by certain abilities, depending on certain engineering abilities
// -- Current is replenished each round depending on power from reactor hardware, and abilities depending on engineering skills
// - Weapons, similar to above but for ship weapon skills

module.exports = {
//     attribute: {
//         defense: {
            
//         },
//         weapon: {
//             skills: { // Mostly this is going to be tactical/weapons
//                 'combat.weapon.mounted': 1 // Weighting for the amount of skill that goes towards this attribute
//             },
//             buffs: {
//                 // This is a question: Where should buffs be registered? Here? In their own module?
//                 // Buffs are generated by completing puzzles.
//                 // A list of buffs of various levels will be generated by players.
//                 // Either a complete list should exist somewhere, or we need a notation that applies them to this.
//             },
//             hardware:
//         },
//         support: {
//             engines: {
                
//             },
//             reactor: {
//             }
//         }
//     },
    // Skills and buffs should probably apply their own attributes to sprites.
    // Also, hardware wouldn't exist for other sprites, so hardware will have to generate permanent buffs.
    capacitor: {
        // Defenses
        ams: {
            
        },
        speed: {
            max: function () {
                // Engine, buffs
            },
            current: 'full',
        }
    }
};
