// Attributes:
// - Visibility
// - Defense
// - Engine
// - Reactor

// Capacitors:
// - Defense
// - Speed
// -- Maximum depends on engine hardware
// -- Moving reduces current
// -- Current is fully replenished each round
// - Energy
// -- Maximum depends on reactor hardware and engineering skills
// -- Current is reduced by certain abilities, depending on certain engineering abilities
// -- Current is replenished each round depending on power from reactor hardware, and abilities depending on engineering skills
// - Weapons, similar to above but for ship weapon skills

module.exports = {
    abilities: [
        'move'
    ],
    attribute: {
        defense: {
            
        },
        weapon: {
            skills: { // Mostly this is going to be tactical/weapons
                // Sheer number of applications for specific skills means they should be configured against the sprite attribute.
                // Maybe this is why the attribute module should contain this.
                'combat.weapon.mounted': 1 // Weighting for the amount of skill that goes towards this attribute
            },
            buffs: {
                // Buffs can also be generated by ship hardware, but permanently.
            }
        },
        support: {
            engines: {
                
            },
            reactor: {
            }
        }
    },
    capacitor: {
        // Defenses
        ams: {
            
        },
        speed: {
            max: function () {
                // Engine, buffs
            },
            current: 'full',
        }
    }
};
