module.exports = {
    skills: { // Mostly this is going to be tactical/weapons
        // Sheer number of applications for specific skills means they should be configured against the sprite attribute.
        // Maybe this is why the attribute module should contain this.
        'combat.weapon.mounted': 1 // Weighting for the amount of skill that goes towards this attribute
    },
    buffs: {
        // Buffs can also be generated by ship hardware, but permanently.
    }
};
