weapons: Weapons
  description: Weapon systems. For people who don't trust other people not to have weapon systems.
  children: &damageTypes
    common: &weapons.common
      rof: Rate of Fire
        description: The rate at which payloads are fired.
      aoe: Area of Effect
        description: The area effected by the payload.
    laser: Laser
      <<: *weapons.common
      description: A monochromatic beam of light, it's brightness so high as to be weaponised.
    plasma: Plasma
      <<: *weapons.common
      description: A beam of particles excited to the point where the electrons have been ripped from their nuclei.
    missile
defenses: Defenses
  children: *damageTypes
reactor: Reactor
  power
  capacity
engines: Engines
crew: Crew
drones
  children:
    common: &drones.common
      stealth
      weapons
      scanners
      engines
  spacemarines
  infantry
  interceptors
  scout
quarters - capacity for crew
scanners
stealth
