weapons:
  label: Weapons
  description: Weapon systems. For people who don't trust other people not to have weapon systems.
  children: &damageTypes
    common: &weaponsCommon
      rof:
        label: Rate of Fire
        description: The rate at which payloads are fired.
      aoe:
        label: Area of Effect
        description: The area effected by the payload.
    laser:
      label: Laser
      <<: *weaponsCommon
      description: A monochromatic beam of light, it's brightness so high as to be weaponised.
    plasma:
      label: Plasma
      <<: *weaponsCommon
      description: A beam of particles excited to the point where the electrons have been ripped from their nuclei.
    missile:
      label: Missile
      <<: *weaponsCommon
      description: A solid projectile which might be self-propelled.
defenses: Defenses
  children: *damageTypes
reactor: Reactor
  power
  capacity
engines: Engines
crew: Crew
drones
  children:
    common: &drones.common
      stealth
      weapons
      scanners
      engines
  spacemarines
  infantry
  interceptors
  scout
quarters - capacity for crew
scanners
stealth
